server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: false

  datasource:
    driver-class-name: ${sonic.datasource.driver-class-name}
    url: jdbc:mysql://${sonic.datasource.host}:${sonic.datasource.port}/${sonic.datasource.database}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${sonic.datasource.username}
    password: ${sonic.datasource.password}

    redis:
      host: ${sonic.redis.host}
      port: ${sonic.redis.port}
      database: ${sonic.redis.database}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

google:
  recaptcha:
    secret: ${sonic.google.recaptcha.secret}