vibe:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sonic_social
    username: root
    password: 1999csysh

  redis:
    host: localhost
    port: 6379
    database: 3